import os
from dotenv import load_dotenv


# loads .env file, will not overide already set enviroment variables (will do nothing when testing, building and deploying)
load_dotenv()


DEBUG = os.getenv('DEBUG', 'False') in ['True', 'true']
PORT = os.getenv('PORT', '8080')
POD_NAME = os.getenv('POD_NAME', 'Pod name not set')

SERVICEPLATFORM_SFTP_REMOTE_DIR = 'IN'
SERVICEPLATFORM_SFTP_HOST = os.environ['SERVICEPLATFORM_SFTP_HOST'].rstrip()
SERVICEPLATFORM_SFTP_USER = os.environ['SERVICEPLATFORM_SFTP_USER'].rstrip()
SERVICEPLATFORM_SSH_KEY_BASE64 = os.environ['SERVICEPLATFORM_SSH_KEY_BASE64'].rstrip()
SERVICEPLATFORM_SSH_KEY_PASS = os.environ['SERVICEPLATFORM_SSH_KEY_PASS'].rstrip()

TRUELINK_SFTP_REMOTE_DIR = '.'
TRUELINK_SFTP_HOST = os.environ['TRUELINK_SFTP_HOST'].rstrip()
TRUELINK_SFTP_USER = os.environ['TRUELINK_SFTP_USER'].rstrip()
TRUELINK_SSH_KEY_BASE64 = os.environ['TRUELINK_SSH_KEY_BASE64'].rstrip()
TRUELINK_SSH_KEY_PASS = None

CLIMATE_DB_USER = os.environ['CLIMATE_DB_USER'].rstrip()
CLIMATE_DB_PASS = os.environ['CLIMATE_DB_PASS'].rstrip()
CLIMATE_DB_HOST = os.environ['CLIMATE_DB_HOST'].rstrip()
CLIMATE_DB_PORT = os.environ['CLIMATE_DB_PORT'].rstrip()
CLIMATE_DB_DATABASE = os.environ['CLIMATE_DB_DATABASE'].rstrip()

FRONTDESK_DB_USER = os.environ['FRONTDESK_DB_USER'].rstrip()
FRONTDESK_DB_PASS = os.environ['FRONTDESK_DB_PASS'].rstrip()
FRONTDESK_DB_HOST = os.environ['FRONTDESK_DB_HOST'].rstrip()
FRONTDESK_DB_PORT = None
FRONTDESK_DB_DATABASE = os.environ['FRONTDESK_DB_DATABASE'].rstrip()

UDDANNELSESSTATISTIK_URL = os.environ['UDDANNELSESSTATISTIK_URL'].rstrip()
UDDANNELSESSTATISTIK_API_KEY = os.environ['UDDANNELSESSTATISTIK_API_KEY'].rstrip()

CUSTOM_DATA_CONNECTOR_HOST = os.environ['CUSTOM_DATA_CONNECTOR_HOST'].rstrip()

JOBINDSATS_API_KEY = os.environ['JOBINDSATS_API_KEY'].rstrip()
JOBINDSATS_URL = os.environ['JOBINDSATS_URL'].rstrip()
JOBINDSATS_CONFIG_FILE = 'jobindsats_jobs_config.json'

SENSUM_IT_SFTP_REMOTE_DIR = '/D:/SFTP-EGDW/'
SENSUM_IT_SFTP_HOST = os.environ['SENSUM_IT_SFTP_HOST'].rstrip()
SENSUM_IT_SFTP_USER = os.environ['SENSUM_IT_SFTP_USER'].rstrip()
SENSUM_IT_SFTP_PASS = os.environ['SENSUM_IT_SFTP_PASS'].rstrip()
SENSUM_CONFIG_FILE = 'sensum_jobs_db_config.json'
SENSUM_DB_USER = os.environ['SENSUM_DB_USER']
SENSUM_DB_PASS = os.environ['SENSUM_DB_PASS']
SENSUM_DB_HOST = os.environ['SENSUM_DB_HOST']
SENSUM_DB_DATABASE = os.environ['SENSUM_DB_DATABASE']
SENSUM_DB_PORT = os.environ['SENSUM_DB_PORT']

CONFIG_LIBRARY_BASE_PATH = 'api/file/etl/'
CONFIG_LIBRARY_USER = os.environ['CONFIG_LIBRARY_USER'].rstrip()
CONFIG_LIBRARY_PASS = os.environ['CONFIG_LIBRARY_PASS'].rstrip()
CONFIG_LIBRARY_URL = os.environ['CONFIG_LIBRARY_URL'].rstrip()

FRONTDESK_DIR = 'Frontdesk'
RANDERS_TEST_SFTP_USER = os.getenv('RANDERS_TEST_SFTP_USER', None)
RANDERS_TEST_SFTP_PASS = os.getenv('RANDERS_TEST_SFTP_PASS', None)
RANDERS_TEST_SFTP_HOST = os.getenv('RANDERS_TEST_SFTP_HOST', None)

FRONTDESK_POSTGRES_DB_HOST = os.environ.get('FRONTDESK_POSTGRES_DB_HOST')
FRONTDESK_POSTGRES_DB_USER = os.environ.get('FRONTDESK_POSTGRES_DB_USER')
FRONTDESK_POSTGRES_DB_PASS = os.environ.get('FRONTDESK_POSTGRES_DB_PASS')
FRONTDESK_POSTGRES_DB_DATABASE = os.environ.get('FRONTDESK_POSTGRES_DB_DATABASE')
FRONTDESK_POSTGRES_DB_PORT = os.environ.get('FRONTDESK_POSTGRES_DB_PORT')

ELASTICSEARCH_HOST = os.getenv("ELASTICSEARCH_HOST")
ELASTICSEARCH_PORT = os.getenv("ELASTICSEARCH_PORT")
ELASTICSEARCH_USER = os.getenv("ELASTICSEARCH_USER")
ELASTICSEARCH_PASS = os.getenv("ELASTICSEARCH_PASS")

ZYLINC_POSTGRES_DB_HOST = os.getenv("ZYLINC_POSTGRES_DB_HOST")
ZYLINC_POSTGRES_DB_USER = os.getenv("ZYLINC_POSTGRES_DB_USER")
ZYLINC_POSTGRES_DB_PASS = os.getenv("ZYLINC_POSTGRES_DB_PASS")
ZYLINC_POSTGRES_DB_DATABASE = os.getenv("ZYLINC_POSTGRES_DB_DATABASE")
ZYLINC_POSTGRES_DB_PORT = os.getenv("ZYLINC_POSTGRES_DB_PORT")

SD_URL = os.environ['SD_URL'].rstrip()
SD_USER = os.environ['SD_USER'].rstrip()
SD_PASS = os.environ['SD_PASS'].rstrip()

LOGIVA_URL = os.environ['LOGIVA_URL'].rstrip()
LOGIVA_USER = os.environ['LOGIVA_USER'].rstrip()
LOGIVA_PASS = os.environ['LOGIVA_PASS'].rstrip()

SD_DELTA_EXCLUDED_DEPARTMENTS_CONFIG_FILE = "sd_delta_excluded_units.csv"
SD_DELTA_TO_MAIL = os.environ['SD_DELTA_TO_MAIL'].rstrip()
SD_DELTA_FROM_MAIL = os.environ['SD_DELTA_FROM_MAIL'].rstrip()
IT_SUPPORT_MAIL = "D-It-Supporten@randers.dk"

DELTA_URL = os.environ['DELTA_URL'].rstrip()
DELTA_CLIENT_ID = os.environ["DELTA_CLIENT_ID"].strip()
DELTA_CLIENT_SECRET = os.environ["DELTA_CLIENT_SECRET"].strip()
DELTA_REALM = '730'
DELTA_AUTH_URL = "https://idp.opus-universe.kmd.dk"

MAIL_SERVER_URL = os.environ['MAIL_SERVER_URL'].rstrip()

ASSET_DB_HOST = os.getenv("ASSET_DB_HOST")
ASSET_DB_USER = os.getenv("ASSET_DB_USER")
ASSET_DB_PASS = os.getenv("ASSET_DB_PASS")
ASSET_DB_DATABASE = os.getenv("ASSET_DB_DATABASE")
ASSET_DB_PORT = os.getenv("ASSET_DB_PORT")

CAPA_CMS_DB_HOST = os.getenv("CAPA_CMS_DB_HOST")
CAPA_CMS_DB_USER = os.getenv("CAPA_CMS_DB_USER")
CAPA_CMS_DB_PASS = os.getenv("CAPA_CMS_DB_PASS")
CAPA_CMS_DB_DATABASE = os.getenv("CAPA_CMS_DB_DATABASE")
CAPA_CMS_DB_PORT = os.getenv("CAPA_CMS_DB_PORT")

ASSET_SFTP_HOST = os.getenv("ASSET_SFTP_HOST")
ASSET_SFTP_USER = os.getenv("ASSET_SFTP_USER")
ASSET_SFTP_PASS = os.getenv("ASSET_SFTP_PASS")

BOM_USERNAME = os.getenv("BOM_USERNAME")
BOM_PASSWORD = os.getenv("BOM_PASSWORD")

BROWSERLESS_URL = os.getenv("BROWSERLESS_URL")
BROWSERLESS_CLIENT_ID = os.getenv("BROWSERLESS_CLIENT_ID")
BROWSERLESS_CLIENT_SECRET = os.getenv("BROWSERLESS_CLIENT_SECRET")

BYGGESAGER_POSTGRES_DB_HOST = os.getenv("BYGGESAGER_POSTGRES_DB_HOST")
BYGGESAGER_POSTGRES_DB_USER = os.getenv("BYGGESAGER_POSTGRES_DB_USER")
BYGGESAGER_POSTGRES_DB_PASS = os.getenv("BYGGESAGER_POSTGRES_DB_PASS")
BYGGESAGER_POSTGRES_DB_DATABASE = os.getenv("BYGGESAGER_POSTGRES_DB_DATABASE")
BYGGESAGER_POSTGRES_DB_PORT = os.getenv("BYGGESAGER_POSTGRES_DB_PORT")

JOBINDSATS_POSTGRES_DB_HOST = os.getenv("JOBINDSATS_POSTGRES_DB_HOST")
JOBINDSATS_POSTGRES_DB_USER = os.getenv("JOBINDSATS_POSTGRES_DB_USER")
JOBINDSATS_POSTGRES_DB_PASS = os.getenv("JOBINDSATS_POSTGRES_DB_PASS")
JOBINDSATS_POSTGRES_DB_DATABASE = os.getenv("JOBINDSATS_POSTGRES_DB_DATABASE")
JOBINDSATS_POSTGRES_DB_PORT = os.getenv("JOBINDSATS_POSTGRES_DB_PORT")

SBSYS_DB_HOST = os.getenv("SBSYS_DB_HOST")
SBSYS_DB_USER = os.getenv("SBSYS_DB_USER")
SBSYS_DB_PASS = os.getenv("SBSYS_DB_PASS")
SBSYS_DB_PORT = os.getenv("SBSYS_DB_PORT")

SD_FLEKSJOBREFUSION_USERNAME = os.getenv("SD_FLEKSJOBREFUSION_USERNAME")
SD_FLEKSJOBREFUSION_PASSWORD = os.getenv("SD_FLEKSJOBREFUSION_PASSWORD")
SD_FLEKSJOBREFUSION_URL = "https://www.silkeborgdata.dk"

TEST_SFTP_HOST = os.getenv("TEST_SFTP_HOST")
TEST_SFTP_USER = os.getenv("TEST_SFTP_USER")
TEST_SFTP_PASS = os.getenv("TEST_SFTP_PASS")

SD_FLEKSJOBREFUSION_SFTP_DIR = '/SD-Fleksjobrefusion/'
SD_FLEKSJOBREFUSION_TO_MAIL = os.environ['SD_FLEKSJOBREFUSION_TO_MAIL'].rstrip()
SD_FLEKSJOBREFUSION_FROM_MAIL = os.environ['SD_FLEKSJOBREFUSION_FROM_MAIL'].rstrip()

SHAREPOINT_POSTGRES_DB_HOST = os.getenv("SHAREPOINT_POSTGRES_DB_HOST")
SHAREPOINT_POSTGRES_DB_USER = os.getenv("SHAREPOINT_POSTGRES_DB_USER")
SHAREPOINT_POSTGRES_DB_PASS = os.getenv("SHAREPOINT_POSTGRES_DB_PASS")
SHAREPOINT_POSTGRES_DB_DATABASE = os.getenv("SHAREPOINT_POSTGRES_DB_DATABASE")
SHAREPOINT_POSTGRES_DB_PORT = os.getenv("SHAREPOINT_POSTGRES_DB_PORT")

API_SERVICE_URL = os.getenv("API_SERVICE_URL")

VOGNPARK_POSTGRES_DB_HOST = os.getenv("VOGNPARK_POSTGRES_DB_HOST")
VOGNPARK_POSTGRES_DB_USER = os.getenv("VOGNPARK_POSTGRES_DB_USER")
VOGNPARK_POSTGRES_DB_PASS = os.getenv("VOGNPARK_POSTGRES_DB_PASS")
VOGNPARK_POSTGRES_DB_DATABASE = os.getenv("VOGNPARK_POSTGRES_DB_DATABASE")
VOGNPARK_POSTGRES_DB_PORT = os.getenv("VOGNPARK_POSTGRES_DB_PORT")
VOGNPARK_SFTP_DIR = '/Vognpark/'

EKKO_URL = 'vps123.basicserver.io'
EKKO_USERNAME = 'randers'
EKKO_PASSWORD = os.getenv("EKKO_PASSWORD")
EKKO_CONFIG_FILE = 'ekko_job_config.json'

ATEA_API_KEY = os.environ['ATEA_API_KEY'].rstrip()
ATEA_URL = os.environ['ATEA_URL'].rstrip()

ASSET_SFTP_DEVICE_FILE_PATH = 'Computers.csv'
ASSET_SFTP_COMM2IG_HISTORICAL_FILE_PATH = '/Historisk_data/Historisk_Comm2ig.csv'
ASSET_SFTP_EAN_ATEA_FILE_PATH = '/Historisk_data/ATEA kundenumre med EAN.xlsx'
ASSET_SFTP_AFDELINGS_EAN_DELTA_FILE_PATH = '/Historisk_data/Afdeling_EAN_Delta.xlsx'

TOPDESK_API_USERNAME = os.getenv("TOPDESK_API_USERNAME")
TOPDESK_API_PASSWORD = os.getenv("TOPDESK_API_PASSWORD")
TOPDESK_API_URL = os.getenv("TOPDESK_API_URL")
TOPDESK_ASSET_FILENAME = 'Asset-Management.csv'
